name: HTTP GET trigger every 5 min for not letting server go into idle mode

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  http_request:
    runs-on: ubuntu-latest
    steps:
      - name: HTTP GET Request
        run: |
<<<<<<< HEAD
          curl https://fixrss.onrender.com/trigger
=======
          curl https://fixrss.onrender.com/trigger
>>>>>>> branch 'main' of https://github.com/RomanHoliday2k22/FixRSS.git
